---
title: Data Processing and Cleaning
author: Tyler Hampton
output: github_document
---

## Natural Earth Data

### Download 
```{r,eval = FALSE}
utils::download.file(
  url = "https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/cultural/ne_10m_populated_places_simple.zip",
  destfile = "C:/Users/tbhampto/Downloads/ne_10m_populated_places_simple.zip"
)
utils::unzip(
  zipfile = "C:/Users/tbhampto/Downloads/ne_10m_populated_places_simple.zip",
  exdir = "data-raw/worldcities"
)
```


### Final Processing

```{r}
worldcities = sf::st_read(file.path(
  "data-raw","worldcities",
  "ne_10m_populated_places_simple.shp"
),quiet=TRUE)

worldcities$adm1name = stringi::stri_trans_general(
  worldcities$adm1name,
  "latin-ascii"
)

worldcities = worldcities[,c(
  "nameascii","featurecla","adm0cap","worldcity",
  "sov0name","adm0name","adm1name",
  "sov_a3","adm0_a3","iso_a2",
  "latitude","longitude",
  "pop_max","pop_min","geometry"
)]

plot(st_geometry(worldcities))
```

```{r, eval=FALSE}
usethis::use_data(worldcities,overwrite=TRUE)
usethis::use_r("worldcities")
```



## Canada Census Information

### Download

[Canada Census Shapefile](https://open.canada.ca/data/en/dataset/5be03a46-8504-40a7-a96c-af195bae0428)

```{r, eval = FALSE}
utils::download.file(
  url = "https://www12.statcan.gc.ca/census-recensement/2011/geo/bound-limit/files-fichiers/gecu000e11a_e.zip",
  destfile = "C:/Users/tyler/Downloads/gecu000e11a_e.zip"
)
utils::unzip(
  zipfile = "C:/Users/tyler/Downloads/gecu000e11a_e.zip",
  exdir = "data-raw/CanadaCensusShapes"
)
```

[Canada Census Pop Data](https://open.canada.ca/data/en/dataset/ece81c43-aa4e-41ef-86c2-3835eb5aa95c)

```{r, eval = F}
utils::download.file(
  url = "https://www12.statcan.gc.ca/census-recensement/2016/dp-pd/hlt-fst/pd-pl/Tables/CompFile.cfm?Lang=Eng&T=701&OFT=FULLCSV",
  destfile = "data-raw/CanadaCensusData/CanadaCensusData.csv"
)
```


### Final Processing

```{r}
can_cdiv = sf::st_read("data-raw/CanadaCensusShapes/gcd_000e11a_e.shp",quiet=TRUE)
plot(sf::st_geometry(can_cdiv))
```

```{r, eval=FALSE}
usethis::use_data(can_cdiv,overwrite=TRUE)
usethis::use_r("can_cdiv")
```


```{r}
can_prov = sf::st_read("data-raw/CanadaCensusShapes/gpr_000e11a_e.shp",quiet=TRUE)
plot(sf::st_geometry(can_prov))
```

```{r, eval=FALSE}
usethis::use_data(can_prov,overwrite=TRUE)
usethis::use_r("can_prov")
```

```{r}
can_cendat = read.csv("data-raw/CanadaCensusData/CanadaCensusData.csv")

can_cendat = can_cendat[,c(
  "Geographic.code",
  "Geographic.name..english",
  "Geographic.type..english",
  "Province...territory..english",
  "Geographic.code..Province...territory",
  "Population..2016",
  "Population..2011",
  "Population....change",
  "Total.private.dwellings..2016",
  "Total.private.dwellings..2011",
  "Total.private.dwellings....change",
  "Land.area.in.square.kilometres..2016",
  "Population.density.per.square.kilometre..2016",
  "National.population.rank..2016",
  "Provincial.territorial.population.rank..2016"
)]

names(can_cendat) = c(
  "CDUID",
  "CDNAME",
  "CDTYPE",
  "PRNAME",
  "PRUID",
  "pop.16",
  "pop.11",
  "pop.chg",
  "dwel.16",
  "dwel.11",
  "dwel.chg",
  "landarea.sqkm",
  "popdens.sqkm",
  "poprank.nat",
  "poprank.prov"
)
  
can_cendat$CDNAME = sapply(can_cendat$CDNAME,function(n){
  if(stringi::stri_enc_isascii(n)){
    return(n)
  }else{
    stringi::stri_trans_general(
      iconv(n, "latin1", "utf-8"),
      "latin-ascii")
    # if(grepl("<",n)){
    #   position = unlist(gregexpr("<",n, fixed = TRUE))
    #   char = substr(n,position,position+3)
    #   sub = paste0("\\u00",substr(char,2,3))
    #   special = stringi::stri_unescape_unicode("\\u00e9")
    #   replace = stringi::stri_trans_general(special, "latin-ascii")
    #   
    #   fixed = gsub(char,replace,n)
    # }
  }
})
  
  
can_cendat$CDTYPE = factor(can_cendat$CDTYPE,
                           levels = unique(can_cendat$CDTYPE),
                           labels = c(
                             "Census division","County","Territoire equivalent",
                             "Municipalite regionale de comte",
                             "United counties","Regional municipality",
                             "District municipality","District",
                             "Regional district","Region","Territory",""
                           )
                           )


head(can_cendat)
```

```{r, eval=FALSE}
usethis::use_data(can_cendat,overwrite=TRUE)
usethis::use_r("can_cendat")
```

## Ontario Land Cover

### Download

```{r, eval = FALSE}
options(timeout=300)
utils::download.file(
  url = "http://www.cec.org/files/atlas_layers/1_terrestrial_ecosystems/1_01_1_land_cover_2015_30m/can_land_cover_2015v3_30m_tif.zip",
  destfile = "C:/Users/tbhampto/Downloads/can_land_cover_2015v3_30m_tif.zip"
)
utils::unzip(
  zipfile = "C:/Users/tbhampto/Downloads/can_land_cover_2015v3_30m_tif.zip",
  exdir = "C:/Users/tbhampto/Downloads"
)
```

```{r, eval = FALSE}
lc_can = raster::raster(file.path(
  "C:/Users/tbhampto/Downloads",
  "can_land_cover_2015v3_30m_tif",
  "CAN_NALCMS_landcover_2015v3_30m",
  "data",
  "CAN_NALCMS_landcover_2015v3_30m.tif"
))
crop = sf::st_set_crs(
  sf::st_as_sf(
    sf::st_sfc(
      sf::st_polygon(
        list(matrix(c(
          c(-83.5,-83.5,-76,-76,-83.5),
          c(41.5,45.5,45.5,41.5,41.5)),ncol=2)
        )
      )
    )
  ),4326
)
names(crop) = "geometry"
sf::st_geometry(crop) <- "geometry"
crop = sf::st_transform(crop,sf::st_crs(lc_can))

ontario_lc = raster::crop(lc_can,crop)

raster::writeRaster(x = ontario_lc,
                    file.path(
  "data-raw","canada_2015_land_cover",
  "CAN_NALCMS_2015_v2_land_cover_30m",
  "landcover_SouthernOntario.tif"
))

```

### Final Processing

```{r, eval = FALSE}
ontario_lc_30m = terra::rast(file.path(
  "data-raw","canada_2015_land_cover",
  "CAN_NALCMS_2015_v2_land_cover_30m",
  "landcover_SouthernOntario.tif"
))

ontario_lc_90m = terra::aggregate(
  ontario_lc_30m,
  fact=3,
  fun=modal,
  na.rm=TRUE)

raster::writeRaster(x = ontario_lc_90m,
                    file.path(
  "data-raw","canada_2015_land_cover",
  "CAN_NALCMS_2015_v2_land_cover_90m",
  "landcover_SouthernOntario.tif"
),overwrite=TRUE)
```

```{r}
ontario_lc = raster::raster(file.path(
  "data-raw","canada_2015_land_cover",
  "CAN_NALCMS_2015_v2_land_cover_90m",
  "landcover_SouthernOntario.tif"
))

plot(ontario_lc)
```


```{r, eval=FALSE}
usethis::use_data(ontario_lc,overwrite=TRUE)
usethis::use_r("ontario_lc")
```

## Canadian Aboveground Biomass


https://ftp.maps.canada.ca/pub/nrcan_rncan/Forests_Foret/canada-forests-attributes_attributs-forests-canada/2011-attributes_attributs-2011/NFI_MODIS250m_2011_kNN_Structure_Biomass_TotalLiveAboveGround_v1.tif